Repository miljodir/md-components, pull requests merged in 2025-06, with the labels that each got.

#298 Add border radius to buttons to match Figma
  packages/css/src/button/button.css
Labels: minor

#302 fix: Correct outline offset of accordionitem to match Figma
  packages/css/src/accordionitem/accordionitem.css
Labels: patch

#303 Add large button variant and fix storybook error
  packages/css/src/button/README.md
  packages/css/src/button/button.css
  packages/react/src/button/MdButton.tsx
  stories/Button.stories.tsx
Labels: minor

#310 Upgrade to eslint 9
  .eslintignore
  .eslintrc.json
  .storybook/manager.js
  eslint.config.mjs
  package-lock.json
  package.json
  packages/react/package.json
  packages/react/src/formElements/MdAutocomplete.tsx
  packages/react/src/formElements/MdFileUpload.tsx
  packages/react/src/formElements/MdMultiAutocomplete.tsx
  packages/react/src/hooks/useDropdown.ts
  packages/react/src/hooks/useFileUpload.ts
  packages/react/src/modal/MdModal.tsx
  packages/react/src/utils/MdClickOutsideWrapper.tsx
  stories/Autocomplete.stories.tsx
  stories/Checkbox.stories.tsx
  stories/CheckboxGroup.stories.tsx
  stories/ChipsStories/FilterChip.stories.tsx
  stories/ChipsStories/InputChip.stories.tsx
  stories/ComboBox.stories.tsx
  stories/ComboBoxGrouped.stories.tsx
  stories/HelpStories/HelpButton.stories.tsx
  stories/HelpStories/HowToUse.stories.tsx
  stories/Icons/deprecated/AllIconsGallery.stories.tsx
  stories/Input.stories.tsx
  stories/Modal.stories.tsx
  stories/MultiAutocomplete.stories.tsx
  stories/MultiSelect.stories.tsx
  stories/RadioButton.stories.tsx
  stories/RadioGroup.stories.tsx
  stories/Select.stories.tsx
  stories/Stepper.stories.tsx
  stories/TextArea.stories.tsx
  stories/Toggle.stories.tsx
  themes/mdir-theme.js
Labels: minor

#318 fix: Errors in css focus visible
  packages/css/src/formElements/combobox/combobox.css
  packages/css/src/formElements/select/select.css
Labels: patch

#319 Storybook accessibilty plugin reported aria issues
  packages/react/src/accordion/MdAccordionItem.tsx
  packages/react/src/loadingSpinner/MdLoadingSpinner.tsx
  packages/react/src/tooltip/MdTooltip.tsx
Labels: patch

#320 Add new component: MdSkipToMainContent
  packages/css/src/index.css
  packages/css/src/skipToMainContent/README.md
  packages/css/src/skipToMainContent/skipToMainContent.css
  packages/react/src/index.tsx
  packages/react/src/skipToMainContent/MdSkipToMainContent.tsx
  stories/SkipToMainContent.stories.tsx
Labels: minor

#321 Add "use client" to MdLoadingSpinner
  packages/react/src/loadingSpinner/MdLoadingSpinner.tsx
Labels: patch

#325 Fix MdCombobox border color
  packages/css/src/formElements/combobox/combobox.css
Labels: patch

#330 Feature/merge branch major
  eslint.config.mjs
  package-lock.json
  packages/css/src/accordion/README.md
  packages/css/src/accordionitem/README.md
  packages/css/src/accordionitem/accordionitem.css
  packages/css/src/formElements/combobox/combobox.css
  packages/css/src/tabs/README.md
  packages/css/src/tabs/tabs.css
  packages/react/src/accordion/MdAccordion.tsx
  packages/react/src/accordion/MdAccordionItem.tsx
  packages/react/src/formElements/MdAutocomplete.tsx
  packages/react/src/formElements/MdCheckboxGroup.tsx
  packages/react/src/formElements/MdComboBox.tsx
  packages/react/src/formElements/MdMultiAutocomplete.tsx
  packages/react/src/formElements/MdMultiSelect.tsx
  packages/react/src/formElements/MdRadioGroup.tsx
  packages/react/src/index.tsx
  packages/react/src/tabs/MdTab.tsx
  packages/react/src/tabs/MdTabTitle.tsx
  packages/react/src/tabs/MdTabs.tsx
  stories/Accordion.stories.tsx
  stories/AccordionItem.stories.tsx
  stories/CheckboxGroup.stories.tsx
  stories/Modal.stories.tsx
  stories/RadioGroup.stories.tsx
Labels: major
